import type { FastifyInstance } from 'fastify'
import type { GerirNegocio } from './servico.js'
export async function registrarRotasDeNegocios(app:FastifyInstance,d:{gerir:GerirNegocio; contexto:(authorization?:string)=>Promise<{negocioId:string;utilizadorId:string;email:string}>}){
 const erro={type:'object',properties:{erro:{type:'object',properties:{codigo:{type:'string'}},required:['codigo']}},required:['erro']} as const
 app.post('/v1/negocios/membros/convites',{schema:{body:{type:'object',additionalProperties:false,required:['email','papel'],properties:{email:{type:'string',format:'email'},papel:{enum:['ADMINISTRADOR','EDITOR','OPERADOR','ANALISTA','FATURACAO']}}},response:{204:{type:'null'},400:erro,403:erro},tags:['Negócios'],summary:'Convidar membro'}},async(req,res)=>{await d.gerir.convidar(req.body,await d.contexto(req.headers.authorization));return res.code(204).send()})
 app.patch('/v1/negocios/membros/:membroId',{schema:{body:{type:'object',additionalProperties:false,properties:{papel:{enum:['PROPRIETARIO','ADMINISTRADOR','EDITOR','OPERADOR','ANALISTA','FATURACAO']},estado:{enum:['ATIVO','REVOGADO']}}},response:{204:{type:'null'},400:erro,403:erro,409:erro},tags:['Negócios'],summary:'Alterar ou revogar membro'}},async(req,res)=>{await d.gerir.alterar({...req.body as object,...req.params as object},await d.contexto(req.headers.authorization));return res.code(204).send()})
 app.post('/v1/negocios/relacoes',{schema:{body:{type:'object',additionalProperties:false,required:['beneficiarioId','tipo'],properties:{beneficiarioId:{type:'string',format:'uuid'},tipo:{enum:['AGENCIA_CLIENTE','PARCEIRO_CLIENTE']}}},response:{204:{type:'null'},400:erro,403:erro},tags:['Negócios'],summary:'Criar relação revogável entre negócios'}},async(req,res)=>{await d.gerir.relacionar(req.body,await d.contexto(req.headers.authorization));return res.code(204).send()})
 app.post('/v1/negocios/membros/convites/:conviteId/aceitacoes',{schema:{response:{200:{type:'object',properties:{dados:{type:'object',properties:{negocioId:{type:'string',format:'uuid'}},required:['negocioId']}},required:['dados']},400:erro,403:erro,409:erro},tags:['Negócios'],summary:'Aceitar convite de membro'}},async(req,res)=>{const r=await d.gerir.aceitarConvite(req.params,await d.contexto(req.headers.authorization));return res.send({dados:r})})
 app.delete('/v1/negocios/relacoes/:relacaoId',{schema:{response:{204:{type:'null'},400:erro,403:erro,404:erro},tags:['Negócios'],summary:'Revogar relação entre negócios'}},async(req,res)=>{await d.gerir.revogarRelacao(req.params,await d.contexto(req.headers.authorization));return res.code(204).send()})
}
