import { randomUUID } from 'node:crypto'
import { Pool } from 'pg'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { RepositorioDeNegociosPostgresql } from './repositorio-postgresql.js'
const url=process.env.URL_DE_BASE_DE_DADOS_DE_INTEGRACAO
describe.skipIf(!url)('negócios em PostgreSQL 18',()=>{
 const pool=new Pool({connectionString:url});const s=`negocios_${randomUUID().replaceAll('-','')}`
 const negocio=randomUUID(),u1=randomUUID(),u2=randomUUID(),m1=randomUUID(),m2=randomUUID()
 beforeAll(async()=>{await pool.query(`CREATE SCHEMA "${s}";CREATE TABLE "${s}".membros_do_negocio(id uuid primary key,negocio_id uuid not null,utilizador_id uuid not null,papel text not null,estado text not null,unique(negocio_id,utilizador_id));CREATE TABLE "${s}".convites_de_membro(id uuid primary key,negocio_id uuid not null,email_normalizado text not null,papel text not null,estado text not null,expira_em timestamptz not null,aceite_em timestamptz);CREATE UNIQUE INDEX convite_${s} ON "${s}".convites_de_membro(negocio_id,email_normalizado) WHERE estado='PENDENTE';CREATE TABLE "${s}".relacoes_entre_negocios(id uuid primary key,concedente_id uuid not null,beneficiario_id uuid not null,tipo text not null,estado text not null,revogada_em timestamptz);INSERT INTO "${s}".membros_do_negocio VALUES('${m1}','${negocio}','${u1}','PROPRIETARIO','ATIVO'),('${m2}','${negocio}','${u2}','PROPRIETARIO','ATIVO')`)})
 afterAll(async()=>{await pool.query(`DROP SCHEMA IF EXISTS "${s}" CASCADE`);await pool.end()})
 it('duas revogações concorrentes preservam exactamente um proprietário',async()=>{const r=new RepositorioDeNegociosPostgresql(pool,s);const x=await Promise.all([r.alterarMembroAtomico({negocioId:negocio,membroId:m1,estado:'REVOGADO'}),r.alterarMembroAtomico({negocioId:negocio,membroId:m2,estado:'REVOGADO'})]);expect(x.filter(Boolean)).toHaveLength(1);const q=await pool.query(`SELECT count(*) n FROM "${s}".membros_do_negocio WHERE papel='PROPRIETARIO' AND estado='ATIVO'`);expect(Number(q.rows[0].n)).toBe(1)})
 it('aceita convite uma vez e expira pendentes',async()=>{const r=new RepositorioDeNegociosPostgresql(pool,s),id=randomUUID();await r.convidar({id,negocioId:negocio,email:'x@e.test',papel:'EDITOR'});const a=await Promise.all([r.aceitarConviteAtomico({conviteId:id,email:'x@e.test',membroId:randomUUID(),utilizadorId:randomUUID(),agora:new Date()}),r.aceitarConviteAtomico({conviteId:id,email:'x@e.test',membroId:randomUUID(),utilizadorId:randomUUID(),agora:new Date()})]);expect(a.filter(Boolean)).toHaveLength(1);expect(await r.expirarConvites(new Date('2999-01-01'))).toBeGreaterThanOrEqual(0)})
 it('FORCE RLS oculta membros de outro negócio',async()=>{await pool.query(`ALTER TABLE "${s}".membros_do_negocio ENABLE ROW LEVEL SECURITY;ALTER TABLE "${s}".membros_do_negocio FORCE ROW LEVEL SECURITY;CREATE POLICY isolamento ON "${s}".membros_do_negocio USING(negocio_id=current_setting('app.negocio_id',true)::uuid)`);const outro=randomUUID();const visiveis=await pool.connect();try{await visiveis.query('BEGIN');await visiveis.query("SELECT set_config('app.negocio_id',$1,true)",[outro]);const q=await visiveis.query(`SELECT * FROM "${s}".membros_do_negocio`);expect(q.rows).toHaveLength(0);await visiveis.query('ROLLBACK')}finally{visiveis.release()}})
})
