import { randomUUID } from 'node:crypto'
import type { Pool, PoolClient } from 'pg'
import type { Estado, RepositorioDoCicloDeVida } from './contratos.js'

export class RepositorioDoCicloDeVidaPostgresql implements RepositorioDoCicloDeVida {
  private readonly s: string
  constructor(private readonly p: Pool, schema='public', private readonly falha?:()=>Promise<void>) { if(!/^[a-z_][a-z0-9_]*$/.test(schema))throw Error('Schema inválido');this.s=`"${schema}"` }
  async papel(n:string,u:string){const r=await this.p.query(`SELECT papel FROM ${this.s}.membros_do_negocio WHERE negocio_id=$1 AND utilizador_id=$2 AND estado='ATIVO'`,[n,u]);return r.rows[0]?.papel??null}
  async transicionar(e:{negocioId:string;experienciaId:string;de:Estado[];para:Estado;agora:Date}){const r=await this.p.query(`UPDATE ${this.s}.experiencias SET estado=$1,atualizado_em=$2 WHERE id=$3 AND negocio_id=$4 AND estado=ANY($5::text[])`,[e.para,e.agora,e.experienciaId,e.negocioId,e.de]);return r.rowCount===1}
  async criarCorrecao(e:{negocioId:string;experienciaId:string;novaVersaoId:string;utilizadorId:string}){return this.tx(async c=>{
    await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[e.experienciaId])
    const q=await c.query(`SELECT versao_publicada_id FROM ${this.s}.experiencias WHERE id=$1 AND negocio_id=$2 AND estado IN('PUBLICADA','PAUSADA') FOR UPDATE`,[e.experienciaId,e.negocioId]);const antiga=q.rows[0]?.versao_publicada_id;if(!antiga)return null
    const n=await c.query(`SELECT numero FROM ${this.s}.versoes_da_experiencia WHERE id=$1`,[antiga]);const numero=Number(n.rows[0].numero)+1
    await c.query(`INSERT INTO ${this.s}.versoes_da_experiencia(id,experiencia_id,numero,estado,criado_por_utilizador_id) VALUES($1,$2,$3,'RASCUNHO',$4)`,[e.novaVersaoId,e.experienciaId,numero,e.utilizadorId])
    await c.query(`INSERT INTO ${this.s}.traducoes_da_experiencia(versao_da_experiencia_id,idioma,titulo,resumo,metadados_de_partilha) SELECT $1,idioma,titulo,resumo,metadados_de_partilha FROM ${this.s}.traducoes_da_experiencia WHERE versao_da_experiencia_id=$2`,[e.novaVersaoId,antiga])
    const blocos=await c.query(`SELECT id,chave_do_bloco,tipo,posicao,configuracao,versao_do_esquema,visibilidade_inicial FROM ${this.s}.blocos WHERE versao_da_experiencia_id=$1 ORDER BY posicao`,[antiga])
    for(const b of blocos.rows){const novo=randomUUID();await c.query(`INSERT INTO ${this.s}.blocos(id,versao_da_experiencia_id,chave_do_bloco,tipo,posicao,configuracao,versao_do_esquema,visibilidade_inicial) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[novo,e.novaVersaoId,b.chave_do_bloco,b.tipo,b.posicao,b.configuracao,b.versao_do_esquema,b.visibilidade_inicial]);await c.query(`INSERT INTO ${this.s}.traducoes_do_bloco(bloco_id,idioma,conteudo) SELECT $1,idioma,conteudo FROM ${this.s}.traducoes_do_bloco WHERE bloco_id=$2`,[novo,b.id])}
    await c.query(`INSERT INTO ${this.s}.politicas_de_disponibilidade(versao_da_experiencia_id,abre_em,expira_em,fuso_horario,modo) SELECT $1,abre_em,expira_em,fuso_horario,modo FROM ${this.s}.politicas_de_disponibilidade WHERE versao_da_experiencia_id=$2`,[e.novaVersaoId,antiga])
    await c.query(`INSERT INTO ${this.s}.regras(id,versao_da_experiencia_id,chave_da_regra,condicoes,acoes,estado,prioridade,tipo_de_gatilho,versao_do_esquema) SELECT gen_random_uuid(),$1,chave_da_regra,condicoes,acoes,'RASCUNHO',prioridade,tipo_de_gatilho,versao_do_esquema FROM ${this.s}.regras WHERE versao_da_experiencia_id=$2`,[e.novaVersaoId,antiga])
    await c.query(`UPDATE ${this.s}.experiencias SET versao_de_rascunho_atual_id=$1 WHERE id=$2`,[e.novaVersaoId,e.experienciaId]);return{versaoAnteriorId:antiga,numero}
  })}
  async publicarCorrecaoAtomica(e:{negocioId:string;experienciaId:string;novaVersaoId:string;versaoAnteriorId:string;soma:string;agora:Date}){return this.tx(async c=>{await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[e.experienciaId]);const nova=await c.query(`SELECT id FROM ${this.s}.versoes_da_experiencia WHERE id=$1 AND experiencia_id=$2 AND estado='RASCUNHO' FOR UPDATE`,[e.novaVersaoId,e.experienciaId]);if(nova.rowCount!==1)return false;const q=await c.query(`UPDATE ${this.s}.experiencias SET versao_publicada_id=$1,versao_de_rascunho_atual_id=NULL,atualizado_em=$2 WHERE id=$3 AND negocio_id=$4 AND versao_publicada_id=$5 AND estado IN('PUBLICADA','PAUSADA') RETURNING id`,[e.novaVersaoId,e.agora,e.experienciaId,e.negocioId,e.versaoAnteriorId]);if(q.rowCount!==1)return false;await c.query(`UPDATE ${this.s}.versoes_da_experiencia SET estado='SUBSTITUIDA' WHERE id=$1`,[e.versaoAnteriorId]);await c.query(`UPDATE ${this.s}.versoes_da_experiencia SET estado='PUBLICADA',publicada_em=$1,soma_de_verificacao=$2 WHERE id=$3`,[e.agora,e.soma,e.novaVersaoId]);await c.query(`UPDATE ${this.s}.pontos_de_acesso SET versao_da_experiencia_id=$1 WHERE experiencia_id=$2 AND estado='ATIVO'`,[e.novaVersaoId,e.experienciaId]);await this.falha?.();return true})}
  private async tx<T>(f:(c:PoolClient)=>Promise<T>){const c=await this.p.connect();try{await c.query('BEGIN');const r=await f(c);await c.query('COMMIT');return r}catch(x){await c.query('ROLLBACK');throw x}finally{c.release()}}
}
